// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"undersea/im_balance/conf"
	"undersea/im_balance/internal/biz"
	"undersea/im_balance/internal/server"
	"undersea/im_balance/internal/service"
)

// Injectors from wire.go:

func initApp() (*app, error) {
	contextContext := context.Background()
	confConf := conf.NewConf()
	heartBeatUseCase := biz.NewHeartBeatUseCase(confConf)
	heartBeatServiceServer := service.NewHeartBeatService(confConf, heartBeatUseCase)
	grpcServer := server.NewGrpcServer(confConf, heartBeatServiceServer)
	balanceUseCase := biz.NewBalanceUseCase(confConf)
	balanceService := service.NewBalanceService(contextContext, balanceUseCase)
	websocketServer := server.NewWebsocketServer(confConf, balanceService)
	mainApp := newApp(contextContext, grpcServer, websocketServer)
	return mainApp, nil
}
