// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"undersea/im_balance/conf"
	"undersea/im_balance/internal/biz"
	"undersea/im_balance/internal/service"
)

// Injectors from wire.go:

func initApp() (*app, error) {
	contextContext := context.Background()
	confConf := conf.NewConf()
	balanceUseCase := biz.NewBalanceUseCase(confConf)
	balanceService := service.NewBalanceService(contextContext, balanceUseCase)
	imManagerUseCase := biz.NewImManagerUseCase(confConf)
	imManagerService := service.NewImManagerService(confConf, imManagerUseCase)
	mainApp := newApp(contextContext, confConf, balanceService, imManagerService)
	return mainApp, nil
}
