// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"undersea/im-api/conf"
	"undersea/im-api/internal/biz"
	"undersea/im-api/internal/data"
	"undersea/im-api/internal/server"
	"undersea/im-api/internal/service"
)

// Injectors from wire.go:

func initApp() (*app, error) {
	contextContext := context.Background()
	confConf := conf.NewConf()
	db, err := data.NewMysql(confConf)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(db)
	userUseCase := biz.NewUserUseCase(userRepo)
	userService := service.NewUserService(userUseCase)
	groupUserRepo := data.NewGroupUserRepo(db, userRepo)
	groupUserUseCase := biz.NewGroupUseCase(groupUserRepo)
	groupUserService := service.NewGroupUserService(groupUserUseCase)
	friendRepo := data.NewFriendRepo(db, userRepo)
	friendUseCase := biz.NewFriendUseCase(friendRepo)
	friendService := service.NewFriendService(friendUseCase)
	httpServer := server.NewHttpServer(confConf, userService, groupUserService, friendService)
	mainApp := newApp(contextContext, httpServer)
	return mainApp, nil
}
