// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"undersea/im-manage/conf"
	"undersea/im-manage/internal/server"
)

// Injectors from wire.go:

func initApp() (*app, error) {
	contextContext := context.Background()
	confConf := conf.NewConf()
	grpcClient := server.NewGrpcClient(contextContext, confConf)
	websocketServer := server.NewWebsocketServer(confConf)
	mainApp := newApp(contextContext, grpcClient, websocketServer)
	return mainApp, nil
}
