// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"undersea/im-balance/conf"
	"undersea/im-balance/internal/biz"
	"undersea/im-balance/internal/data"
	"undersea/im-balance/internal/server"
	"undersea/im-balance/internal/service"
)

// Injectors from wire.go:

func initApp() (*app, error) {
	contextContext := context.Background()
	confConf := conf.NewConf()
	client, err := data.NewRedisClient(contextContext, confConf)
	if err != nil {
		return nil, err
	}
	balanceRepo := data.NewBalanceRepo(client)
	heartBeatUseCase := biz.NewHeartBeatUseCase(confConf, balanceRepo)
	heartBeatServiceServer := service.NewHeartBeatService(confConf, heartBeatUseCase)
	grpcServer := server.NewGrpcServer(confConf, heartBeatServiceServer)
	balanceUseCase := biz.NewBalanceUseCase(confConf, balanceRepo)
	balanceService := service.NewBalanceService(contextContext, balanceUseCase)
	websocketServer := server.NewWebsocketServer(confConf, balanceService)
	mainApp := newApp(contextContext, grpcServer, websocketServer)
	return mainApp, nil
}
